### ISSUE TITLE
CasualBroadcast.prototype.send Bug

### ISSUE THREAD

**Issue by folkvir** [Chat-Wane/CausalBroadcastDefinition#1]
Hi ! 

I found a difference in your code between crate-core.bundle.debug.js and  casualbroacast.js. I think it's more an oversight rather than a mistake or maybe it's a missed commit.
If you check the "CausalBroadcast.prototype.send"  (line 60, file: casualbroadcast.js)  you will see a problem.

``` javascript
CausalBroadcast.prototype.send = function(message, id, isReady){
    // #1 get the neighborhood and create the message
    var links = this.source.getPeers();
    ....
}
```

Whithout a number as parameter, your function always bug on links.o or links.i.
You can solve it by adding Number.MAX_VALUE, 

``` javascript
CausalBroadcast.prototype.send = function(message, id, isReady){
    // #1 get the neighborhood and create the message
    var links = this.source.getPeers(Number.MAX_VALUE);
    ....
}
```

As you solved it in your crate-core bundle ! 

I hope it was helpfull !

Arnaud,
Master Student, University of Nantes.

**Comment by Chat-Wane** [comment]
Hi !

Indeed, I forgot to push a lot of code on the spray-wrtc module. The github version was v0.0.2 while the current version  is v0.1.1. (In this version getPeers() becomes implicitly getPeers(Number.MAX_VALUE) ).

Same mistake for crate-core which was v0.0.6 on github while current version is v0.0.8.

Hopefully I did not forget anything else...

Thanks for the report btw !

Brice.

**Comment by folkvir** [comment]
Nice, I'll be waiting for  a new version ! Thank you for your reply !

Arnaud.

**Comment by Chat-Wane** [comment]
I mean: I just pushed the latest versions on Github. Should be fine now.
